services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy --schema apps/auth/prisma/schema.prisma && npx prisma generate --schema apps/auth/prisma/schema.prisma && yarn run start:dev auth"
    ports:
      - "4000:4000"
    env_file:
      - apps/auth/.env
    volumes:
      - .:/usr/src/app
    networks:
      - sergo-network
networks:
  sergo-network:
    driver: bridge

